### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jctheone23** [polo-sec/writing#2]
When running the shell, it gives me a syntax error. Deleted some blank lines and still getting an error.
<img width="842" alt="Screen Shot 2021-04-09 at 2 00 05 PM" src="https://user-images.githubusercontent.com/20998274/114230359-adedd880-993e-11eb-8dfc-7fbbffe0b1a1.png">

**Comment by imsiddhant** [comment]
+1
Facing same issue while solving THM Box
